### ISSUE TITLE
Allow Banded Jacobian Matrix

### ISSUE THREAD

**Issue by YingboMa** [JuliaNLSolvers/NLsolve.jl#113]
It will be really nice to add banded Jacobian matrix support in `NLsolve.jl`.

**Comment by ChrisRackauckas** [comment]
I think this would be mostly solved by 

https://github.com/JuliaNLSolvers/NLsolve.jl/issues/83

since the user can just set it to use a banded linear solver. That doesn't fix the memory usage though, so it would still be nice to allow the user to give a type which is the suggested Jacobian type. This would be a nice way IMO to handle sparsity and other things like Triangular Jacobians too.

**Comment by YingboMa** [comment]
I suggest that there should be a functionality like `nlsolve(f!, u0, jac_upper=N, jac_lower=M)`, so user doesn't need to calculate the Jacobian matrix explicitly and factorize the banded Jacobian from there.

**Comment by pkofod** [comment]
Why would that be superior to simply supplying Jacobians of any type?

**Comment by ChrisRackauckas** [comment]
It wouldn't.

**Comment by pkofod** [comment]
This should work now. If it doesn't, it's a bug and we'll reopen. The syntax is to supply the OnceDifferentiable instance directly
``` 
OnceDifferentiable(f!, j!, fj! x, F, J)
```
where `F` is a typical storage for the residuals and `J` is the banded matrix
